![Scikitlearn](https://upload.wikimedia.org/wikipedia/commons/0/05/Scikit_learn_logo_small.svg)

## SimpleImputer

In [12]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

dtst=pd.read_csv('credit_immo.csv')
print(dtst.shape)
dtst_describe=dtst.describe()
#Affiche le nom des colonnes
dtst_col=dtst.columns



(19, 10)


In [6]:
'''Définition des colonnes formant les entrées et les sorties'''

#Les entrées ne prennent pas en compte la solvabilité et les noms
X=dtst.iloc[:,-9:-1].values
#La sortie correspond à la solvabilité des clients
Y=dtst.iloc[:,-1].values

print(X[:,0:1])

[[3.0]
 [5.0]
 [0.0]
 [4.0]
 [0.0]
 [0.0]
 [-1.0]
 [-3.0]
 [nan]
 [3.0]
 [2.0]
 [0.0]
 [-3.0]
 [0.0]
 [1.0]
 [0.0]
 [8.0]
 [3.0]
 [4.0]]


In [8]:
'''Transformation des valeurs manquantes (nan) en moyenne'''

imptr=SimpleImputer(missing_values=np.nan, strategy='mean')

#Adapter le model aux données
imptr.fit(X[:,0:1])


#Adapter le model aux données

X[:,0:1] = imptr.transform(X[:,0:1])

print(X[:,0:1])


[[3.0]
 [5.0]
 [0.0]
 [4.0]
 [0.0]
 [0.0]
 [-1.0]
 [-3.0]
 [1.4444444444444444]
 [3.0]
 [2.0]
 [0.0]
 [-3.0]
 [0.0]
 [1.0]
 [0.0]
 [8.0]
 [3.0]
 [4.0]]


## LabelEncoder

In [9]:
##Méthode 1 avec LabelEncoder

LabEnc_X = LabelEncoder()

print(X[:,2])
#Encodage de la colonne 2 du tableau qui est catégorielle --> 3 catégorie donc 1, 2 et 3
X[:,2]=LabEnc_X.fit_transform(X[:,2])
print("***************")
print(X[:,2])


['CDI' 'CDI' 'CDI' 'CDD' 'CDD' 'INTERIM' 'CDI' 'INTERIM' 'CDI' 'CDI' 'CDI'
 'CDD' 'INTERIM' 'CDI' 'CDD' 'ENTRPRENEUR' 'CDI' 'CDI' 'CDI']
***************
[1 1 1 0 0 3 1 3 1 1 1 0 3 1 0 2 1 1 1]


## StandardScaler

In [14]:
#Récupération des données
dataset_vin = pd.read_csv('qualite-vin-rouge.csv',',')
#Récupération des valeurs d'entrées et de sortie
X_vin = dataset_vin.iloc[:,-11:-1].values
print(X_vin.shape)
Y_vin = dataset_vin.iloc[:,-1].values.reshape(-1,1)
print(Y_vin.shape)

#Séparation en 2 jeux de données
X_vin_train, X_vin_test, Y_vin_train, Y_vin_test = train_test_split(X_vin, Y_vin, test_size=0.2, random_state=0)

#Normalisation des valeurs de X
scaler = StandardScaler()

print(X_vin_test)


X_vin_test = scaler.fit_transform(X_vin_test)
print("=====================================")
print(X_vin_test)


(1599, 10)
(1599, 1)
[[ 0.47   0.43   2.1   ...  3.17   0.76  10.8  ]
 [ 0.82   0.     4.1   ...  3.36   0.53   9.6  ]
 [ 0.29   0.33   2.05  ...  3.26   0.84  11.7  ]
 ...
 [ 0.34   0.42   1.8   ...  3.18   0.55  11.4  ]
 [ 0.765  0.04   1.6   ...  3.29   0.54   9.7  ]
 [ 0.32   0.42   2.3   ...  3.27   0.55  12.3  ]]
[[-0.29922497  0.8557103  -0.31177699 ... -0.93785052  0.72205872
   0.31519731]
 [ 1.83333604 -1.39006001  1.32310441 ...  0.28055357 -0.85116573
  -0.79369656]
 [-1.39597062  0.33343814 -0.35264903 ... -0.36071174  1.26926723
   1.14686771]
 ...
 [-1.09131905  0.80348308 -0.5570092  ... -0.87372399 -0.7143636
   0.86964424]
 [ 1.49821931 -1.18115114 -0.72049734 ... -0.16833214 -0.78276467
  -0.70128874]
 [-1.21317968  0.80348308 -0.14828885 ... -0.29658521 -0.7143636
   1.70131464]]
