<h1><center> Exercices Numpy </center></h1>


## 1. Importez le package numpy sous le nom np

In [1]:
import numpy as np

## 2. Créer un vecteur des valeurs 0 de taille 15

In [6]:
Z = np.zeros(15)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 3. Créez un vecteur nul de taille 10 mais la cinquième valeur qui est 1

In [30]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 4. Créez un vecteur avec des valeurs allant de 10 à 49

In [31]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 5. Inverser un vecteur 

In [32]:
Z = np.arange(5)
Z = Z[::-1]
print(Z)

[4 3 2 1 0]


## 6. Créez un vecteur aléatoire de taille 30 et trouvez la valeur moyenne

In [33]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5213455678774359


## 7. Rechercher des indices d'éléments non nuls à partir de [0,3,1,2,0,0,4,0]

In [34]:
nz = np.nonzero([0,3,1,2,0,0,4,0])
print(nz)

(array([1, 2, 3, 6], dtype=int64),)


## 8. Étant donné un tableau 1D, négativez tous les éléments qui sont entre 2 et 7.

In [6]:
Z = np.arange(11)
Z[(2 < Z) & (Z < 7)] *= -1
print(Z)

[ 0  1  2 -3 -4 -5 -6  7  8  9 10]


## 9. Comment extraire tous les nombres entre un intervalle donné d'un tableau numpy?

In [36]:

a = np.array([2, 6, 1, 9, 10, 3, 27])

a[(a > 5) & (a < 10)]

array([6, 9])

## 10. Comment trouver des valeurs communes entre deux tableaux?

In [37]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 2 3 5 7]


##  11. Comment concaténer deux tableaux verticalment & horizontalement

In [38]:
A = [0, 1, 2, 3, 4]
B = [5, 6, 7, 8, 9]
V=np.vstack((A, B))
print(V)

H=np.hstack((A, B))
print(H)


[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


## 12. Créer une matrice alétoire de taille (6,4)

In [3]:
Z=np.random.randn(6,4)
print(Z)

[[-0.47377192 -0.19203217  0.38101304  0.48607273]
 [ 1.55952959 -1.05385936  0.03816005 -0.00227513]
 [-0.65138465  0.24377342 -0.56312582  1.10430745]
 [-0.67872859 -0.04437308 -0.27105617 -0.49168707]
 [ 1.26822151  0.36517211  0.56586987 -0.34133955]
 [ 1.04387156 -0.67661764 -0.14332409 -1.9316264 ]]


## 13. Faire le transposé une matrice 

In [4]:
Z=np.random.randint(5, size=(2, 4))
Z = Z.T
print(Z)

[[2 2]
 [1 2]
 [2 0]
 [4 3]]


## 14. Créer une matrice d'identité de taille 3x3

In [42]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 15. Créer un tableau 3x5x5 avec des valeurs aléatoires

In [43]:
Z = np.random.random((3,5,5))
print(Z)

[[[0.11809942 0.59425674 0.59217049 0.23565535 0.29571788]
  [0.04294196 0.0603795  0.16138301 0.61656553 0.53924384]
  [0.12026426 0.73707485 0.17229268 0.97773171 0.86595787]
  [0.90672925 0.00945237 0.88927931 0.11843568 0.69035624]
  [0.75650736 0.46141008 0.62214368 0.94990351 0.98780218]]

 [[0.83384142 0.21869916 0.66269336 0.08613035 0.53563584]
  [0.87054127 0.47995801 0.79945659 0.15638151 0.40816557]
  [0.20750269 0.4447351  0.16391486 0.58217283 0.5653036 ]
  [0.40097872 0.64684125 0.06754157 0.16877554 0.54630037]
  [0.60580556 0.73756266 0.4613242  0.6981884  0.62241682]]

 [[0.05642842 0.26668163 0.6587946  0.67295584 0.71870731]
  [0.66855914 0.93600913 0.8840649  0.82927194 0.63922029]
  [0.43079509 0.76046033 0.45787309 0.21059526 0.60079728]
  [0.7648703  0.61321301 0.57638005 0.68978209 0.64319506]
  [0.30831427 0.53404256 0.00501522 0.14746457 0.68286349]]]


## 16. Créez un tableau 10x10 avec des valeurs aléatoires et trouvez les valeurs minimum et maximum

In [44]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0030307170413794715 0.995010873810325


## 17. Créez un tableau 2D avec 1 sur les extrémités et 0 à l'intérieur

In [45]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 18. Créer une matrice 5x5 avec des valeurs 1,2,3,4 juste en dessous de la diagonale

In [46]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## 19. Normaliser une matrice aléatoire 5x5

In [47]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.15292882 -1.62473563  1.55643971  0.4437343  -1.08170152]
 [-0.7990665   0.30179172  0.48991843  1.33694596 -0.55341276]
 [ 0.35375856  0.01816986 -1.56526905  1.52429529 -1.16043026]
 [ 0.54379333  1.35198153 -1.44435988  0.71024929  0.72350415]
 [-0.3899028  -1.46995324  0.31088634  1.01691833 -0.74648397]]


## 20. Multiplier une matrice 5x3 par une matrice 3x2

In [53]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


## 21. Comment obtenir les positions où on a les même éléments dans les deux tableaux ?

In [54]:
# exemple A= [1,2,3,2,3,4,3,4,5,6] et B=[7,2,10,2,7,4,9,4,9,8] ==> le résultat est [1, 3, 5, 7]

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.where(a == b))

(array([1, 3, 5, 7], dtype=int64),)


## 22. Comment trouver l'index de la n ième répétition d'un élément dans un tableau 1D

In [3]:
#n=5
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
# print(np.where(x == 1))
np.where(x == 1)[0][4]

(array([ 0,  2,  3,  7,  8, 10, 11], dtype=int64),)


8

## 23. Comment soustraire un tableau 1d d'un tableau 2d, où chaque élément du tableau 1d soustrait de la ligne respective?

In [2]:
# exemple matrice = [[[4,4,4],[5,5,5],[6,6,6]]]  vecteur=[2,3,4] 

#  resultat  
# [[2 2 2]
# [2 2 2]
# [2 2 2]]


a_2d = np.array([[4,4,4],[5,5,5],[6,6,6]])
b_1d = np.array([2,3,4])

print("Solution")
a_2d - b_1d[:, None]

(3,)
Solution
(3, 1)


array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

## 24. Comment supprimer toutes les valeurs manquantes d'un tableau numpy? (avec for)

In [52]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
print(a)
a[[not np.isnan(x) for x in a]]

[ 1.  2.  3. nan  5.  6.  7. nan]


array([1., 2., 3., 5., 6., 7.])