<h1><center> Exercices Numpy </center></h1>


## 1. Importez le package numpy sous le nom np

In [4]:
import numpy as np

## 2. Créer un vecteur des valeurs 0 de taille 100

In [6]:
# Résultat attendu
# [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
#  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
#  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
#  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
#  0. 0. 0. 0.]


In [10]:
np.zeros([1,100])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

## 3. Créez un vecteur nul de taille 10 mais la cinquième valeur qui est 1

In [11]:
# Résultat attendu [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [17]:
a = np.zeros([1,10])
a[0,4] = 1.
a

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

## 4. Créez un vecteur avec des valeurs allant de 10 à 49

In [18]:
# [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
#  34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

In [20]:
b = np.arange(10, 50, 1)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 5. Créer et Inverser un vecteur 

In [27]:
b[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## 6. Créez un vecteur aléatoire de taille 30 et trouvez la valeur moyenne

In [36]:
c = np.random.randint(-100,100,30)
print(c)
np.mean(c)

[-41  66  88  -8 -73  91 -53  21  43 -51  89   1 -62 -42  -1 -33  58  -1
   2   1  43   3 -76  87  81  57 -12   0  24 -71]


7.7

In [37]:
c = np.random.rand(30)
print(c)
np.mean(c)

[0.18328535 0.57393321 0.39573942 0.64977247 0.25459299 0.79033553
 0.84900914 0.98406924 0.23721935 0.70409923 0.23582012 0.92448276
 0.82940974 0.80790226 0.39401454 0.45189246 0.74450562 0.30146584
 0.62096681 0.28120378 0.84144261 0.2628697  0.08397893 0.05123914
 0.73966157 0.00642516 0.43035082 0.53541114 0.0604945  0.0968525 ]


0.47741486529193544

## 7. Rechercher des indices d'éléments non nuls à partir de [0,3,1,2,0,0,4,0]

In [50]:
# Exemple [0,3,1,2,0,0,4,0]==> résultat [1, 2, 3, 6]
d = np.array([0,3,1,2,0,0,4,0])

In [51]:

np.where(d!=0)

(array([1, 2, 3, 6], dtype=int64),)

In [52]:
np.nonzero(d)

(array([1, 2, 3, 6], dtype=int64),)

## 8. Étant donné un tableau 1D, négativez tous les éléments qui sont entre 2 et 7.

In [5]:
#Exemple [ 0  1  2  3  4  5  6  7  8  9 10] ==> résultat [ 0  1  2 -3 -4 -5 -6  7  8  9 10]
e = np.arange(11)
print(e)

e[(2 < e) & (e < 7)] *= -1
print(e)

#np.where(np.logical_and(e>=2, e<=7), e, -1*e)
#np.where(e>=2, e, -1*e)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -3 -4 -5 -6  7  8  9 10]


## 9. Comment extraire tous les nombres entre une intervalle donné d'un tableau numpy?

In [7]:
# Exemple [2, 6, 1, 9, 10, 3, 27] ==> résultat  pour l'intervalle ]5,10[  ==>    [6, 9]
f = np.array([2, 6, 1, 9, 10, 3, 27])

f[np.where(np.logical_and(f>=5, f<10))]

array([6, 9])

In [8]:
f[(f > 5) & (f < 10)]

array([6, 9])

## 10. Comment trouver des valeurs communes entre deux tableaux?

In [9]:
# Exemple T1=[8 2 8 4 8 0 9 7 4 2] et T2 =[1 7 2 3 2 0 1 2 8 7] ==> resultat [0 2 7 8]
f2 = np.array([2, 0, -1, -9, 10, 4, 27])

f[(f == f2)]

array([ 2, 10, 27])

In [10]:
print(np.intersect1d(f,f2))

[ 2 10 27]


##  11. Comment concaténer deux tableaux verticalment & horizontalement

In [38]:
# A = [0, 1, 2, 3, 4]        
# B = [5, 6, 7, 8, 9]

# Vertical
# [[0 1 2 3 4]
#  [5 6 7 8 9]]

# Horizontal
# [0 1 2 3 4 5 6 7 8 9]


[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [15]:
A = [0, 1, 2, 3, 4]       
B = [5, 6, 7, 8, 9]

horizontal = np.concatenate((A,B), axis=0)
print(horizontal)

horizontal2 = np.hstack((A,B))
print(horizontal)


vertical = np.stack((A,B), axis=0)
print(vertical)
vertical2 = np.vstack((A,B))
print(vertical)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## 12. Créer une matrice alétoire de taille (6,4)

In [135]:
g = np.random.randn(6,4)
g

array([[ 0.61924962, -0.05212241,  0.65678214,  0.91420908],
       [-1.09953597, -0.31138348, -1.09388498, -0.70896561],
       [ 0.82945244, -2.46797901,  0.02240707, -0.81735862],
       [ 1.30583578, -0.53705786, -0.01975698, -0.38812878],
       [ 0.25135056,  1.01265399,  0.09057453,  1.29960841],
       [-0.48695742,  1.96688872,  1.61949789, -0.9936187 ]])

## 13. Faire le transposé une matrice 

In [136]:
# [[1 4 3 1]
#  [3 3 3 1]]


#Résultat
# [[1 3]
#  [4 3]
#  [3 3]
#  [1 1]]

print(g.T)

[[ 0.61924962 -1.09953597  0.82945244  1.30583578  0.25135056 -0.48695742]
 [-0.05212241 -0.31138348 -2.46797901 -0.53705786  1.01265399  1.96688872]
 [ 0.65678214 -1.09388498  0.02240707 -0.01975698  0.09057453  1.61949789]
 [ 0.91420908 -0.70896561 -0.81735862 -0.38812878  1.29960841 -0.9936187 ]]


## 14. Créer une matrice d'identité de taille 3x3

In [143]:
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]

h = np.eye(3,3)
h

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 15. Créer un tableau 3x5x5 avec des valeurs aléatoires

In [16]:
j = np.random.random((3,5,5))
j

array([[[0.21897911, 0.0529576 , 0.65051569, 0.0955033 , 0.67180407],
        [0.81093847, 0.85160873, 0.70446392, 0.18926945, 0.31023746],
        [0.04851101, 0.93279194, 0.33104047, 0.59182309, 0.4485337 ],
        [0.74634802, 0.53602852, 0.09244792, 0.53623717, 0.01107223],
        [0.3185185 , 0.74728062, 0.87630629, 0.36778016, 0.97435536]],

       [[0.87559303, 0.89287898, 0.05156544, 0.07882536, 0.7528546 ],
        [0.98108752, 0.69026542, 0.17664293, 0.82965455, 0.21824105],
        [0.3308885 , 0.76374559, 0.86183448, 0.77960928, 0.47616974],
        [0.41044667, 0.88577151, 0.83351893, 0.55967083, 0.45607593],
        [0.86960033, 0.78373328, 0.21891959, 0.69476395, 0.17882736]],

       [[0.47967394, 0.14208689, 0.51983586, 0.3062365 , 0.45552441],
        [0.81058293, 0.71661902, 0.4459921 , 0.71972252, 0.08126091],
        [0.15170434, 0.90446608, 0.11798392, 0.80399239, 0.29257254],
        [0.06093621, 0.32953949, 0.25050398, 0.58471017, 0.30955892],
        [0.74055

## 16. Créez un tableau 10x10 avec des valeurs aléatoires et trouvez les valeurs minimum et maximum

In [22]:
j = np.random.rand(10,10)
j

array([[0.39199757, 0.82444283, 0.82673688, 0.86822535, 0.88491809,
        0.27582512, 0.40447145, 0.86967358, 0.87689508, 0.51337649],
       [0.29599672, 0.91954887, 0.66319446, 0.40312943, 0.69407987,
        0.07044799, 0.23812318, 0.76620414, 0.58821288, 0.32407795],
       [0.48516323, 0.59128449, 0.69559318, 0.59300382, 0.04386841,
        0.32174837, 0.01136079, 0.88825108, 0.1233696 , 0.02725251],
       [0.34524349, 0.73160579, 0.22072363, 0.11584007, 0.89092412,
        0.98012349, 0.2350418 , 0.17026145, 0.27860592, 0.68191593],
       [0.17180264, 0.34687072, 0.38331415, 0.86719493, 0.38412165,
        0.33887046, 0.26267373, 0.77937246, 0.66437094, 0.74608106],
       [0.12586893, 0.5064881 , 0.64722852, 0.82652946, 0.53689863,
        0.08615396, 0.30636902, 0.60404395, 0.6354178 , 0.88396465],
       [0.40709058, 0.27699995, 0.84948272, 0.62590181, 0.80323091,
        0.96943768, 0.863978  , 0.71321927, 0.83678938, 0.81055511],
       [0.12680319, 0.66347476, 0.1618343

In [23]:
np.min(j)

0.011360791652553215

In [24]:
np.max(j)

0.9888421131899706

## 17. Créez un tableau 2D avec 1 sur les extrémités et 0 à l'intérieur

In [25]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [27]:
k = np.zeros([8,8])
print(k)
print(np.pad(k,(1,1),'constant', constant_values=(1, 1)))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 18. Créer une matrice 5x5 avec des valeurs 1,2,3,4 juste en dessous de la diagonale

In [191]:
v=np.array([1,2,3,4])
np.diag(v,-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

## 19. Normaliser une matrice aléatoire 5x5

[[0.0650945  0.20525857 0.11716133 0.67087742 0.57168485]
 [0.14735448 0.34220235 0.65276007 0.87120328 0.23425354]
 [0.3776236  0.92831673 0.73831609 0.81550111 0.5012641 ]
 [0.07843377 0.60976242 0.50814382 0.56183294 0.29286659]
 [0.06238211 0.71709572 0.67913708 0.23247665 0.24750943]]
[[-1.44307345 -0.91639946 -1.24742954  0.83318839  0.46046696]
 [-1.13397717 -0.40182586  0.76511145  1.58592353 -0.8074493 ]
 [-0.26872859  1.8005304   1.08659278  1.37661965  0.19585721]
 [-1.39295044  0.60354549  0.22170814  0.42344789 -0.58720761]
 [-1.45326542  1.0068561   0.86422447 -0.81412605 -0.75763956]]


## 20. Multiplier une matrice 5x3 par une matrice 3x2

Matrice 1
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Matrice 2
[[1. 1.]
 [1. 1.]
 [1. 1.]]
=====Résultat=====
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


## 21. Comment obtenir les positions où on a les même éléments dans les deux tableaux ?

Tableau 1
[1 2 3 2 3 4 3 4 5 6]
Tableau 2
[ 7  2 10  2  7  4  9  4  9  8]
=====Résultat=====
(array([1, 3, 5, 7], dtype=int64),)


## 22. Comment trouver l'index de la n ième répétition d'un élément dans un tableau 1D

In [23]:
#n=5


## 23. Comment soustraire un tableau 1d d'un tableau 2d, où chaque élément du tableau 1d soustrait de la ligne respective?

In [24]:
# exemple matrice = [[[4,4,4],[5,5,5],[6,6,6]]]  vecteur=[2,3,4] 

#  resultat  
# [[2 2 2]
# [2 2 2]
# [2 2 2]]



## 24. Comment supprimer toutes les valeurs manquantes d'un tableau numpy? (avec for)

[ 1.  2.  3. nan  5.  6.  7. nan]


array([1., 2., 3., 5., 6., 7.])